### ISSUE TITLE
Didn't accept my pull request

### ISSUE THREAD

**Issue by InsanePrawn** [finrod09/factorio-mod-switcher#4]
and fucked things up on his own instead

0/10
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)

![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)
![dickbutt](https://cloud.githubusercontent.com/assets/7735910/5993191/ca892b58-aa47-11e4-8f4e-8589cea93b7a.png)

**Comment by finrod09** [comment]
dealwithit
